### ISSUE TITLE
Database names in URLs are prefixed with PouchDB.prefix

### ISSUE THREAD

**Issue by tyler-johnson** [pouchdb/http-pouchdb#1]
It seems that @slaskis was not wrong in his issue pouchdb/pouchdb#3923:

> I've finally had time to attempt to move away from my hack to your slightly more official version but I can't get it to work (tried with PouchDB 3.6.0 and 3.5.0).
> 
> For some reason it tries to connect to `https://hostname.com/_pouch_abc/` where abc is the db.

I too was having the same issue, however setting `PouchDB.prefix = ''` was a less than ideal solution for me.

After some code hunting, I have realized that the main problem is PouchDB's `parseAdapter()`. It returns `'http'` for names that start with `http://`, otherwise it just prefixes the name with `Pouchdb.prefix`.

I was able to fix this by setting the http adapter's `use_prefix` to `false`:

``` js
Pouchdb.adapters.http.use_prefix = false;
```

Ideally this solution (or some other solution) would baked directly into http-pouchdb or even pouchdb, so I don't need to include this at the top of my script.

**Comment by marten-de-vries** [comment]
Confirmed. I'm not entirely sure if that's the best fix, but it works and I don't know anything better at the moment. The whole project is a hack anyway. Thanks for investigating, will soon commit + publish fix.

**Comment by marten-de-vries** [comment]
Fixed in npm version 1.1.1; commit 839360a7e00b0c51f2d56de72a100536f927b1b0.
