### ISSUE TITLE
Building with browserify fails with "Cannot find module 'es3ify'"

### ISSUE THREAD

**Issue by tyler-johnson** [pouchdb/http-pouchdb#2]
In the package.json, `es3ify` is listed as a transform for Browserify but since `es3ify` is under `devDependencies` it is not installed when I install http-pouchdb. Can you move `es3ify` up as a dependency? Thanks.

**Comment by marten-de-vries** [comment]
I'm starting to have the opinion that es3ify should only be used as a global transform, so the proper fix would be to remove it completely.

**Comment by marten-de-vries** [comment]
Thanks for reporting, I hope this fix helps. If it doesn't for some reason, feel free to reopen.
